#!/bin/bash

### autostart ###
sxhkd -c ~/.config/bspwm/sxhkdrc &
feh --bg-fil ~/.config/bspwm/wp.jpg & 
compton --config ~/.config/bspwm/compton.conf & 
xautolock -time 15 -locker 'slock' &
xfce4-power-manager &
redshift -l 0.918550:104.466507 &
urxvt -name task -e htop &

###  border & gap settings ###
bspc config window_gap 0
bspc config border_width 2
bspc config focused_border_color '#12826c'
bspc config normal_border_color '#2d2d2d'

### additional settings ###
bspc monitor -d 1 2 3 4 5 6 
bspc config borderless_monocle true 
bspc config leaf_monocle true
bspc config split_ratio 0.50
bspc config focus_follows_pointer true 

### bspwm rules ###
bspc rule -a '*:*' split_dir=east
bspc rule -a Lxappearance state=floating center=true
bspc rule -a URxvt:editor state=floating center=true
bspc rule -a Firefox desktop=1
bspc rule -a Thunar desktop=3
bspc rule -a URxvt:music state=floating center=true desktop=5
bspc rule -a URxvt:vpn state=floating center=true 
bspc rule -a URxvt:task desktop=6
